name: base
channels:
  - nvidia/label/cuda-11.3.0
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - conda=4.10.3=py38h06a4308_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - cryptography=3.4.7=py38hd23ed53_0
  - cuda-nvcc=11.3.58=h2467b9f_0
  - idna=2.10=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1s=h7f8727e_0
  - pip=21.1.3=py38h06a4308_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - audioread==3.0.0
    - boto3==1.26.67
    - botocore==1.29.67
    - contourpy==1.0.7
    - cycler==0.11.0
    - decorator==5.1.1
    - fonttools==4.38.0
    - jmespath==1.0.1
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - librosa==0.9.2
    - llvmlite==0.39.1
    - matplotlib==3.6.3
    - ninja==1.11.1
    - nose==1.3.7
    - numba==0.56.4
    - numpy==1.19.1
    - packaging==23.0
    - pillow==9.4.0
    - pooch==1.6.0
    - protobuf==3.19.3
    - pyclif==0.3
    - pykaldi==0.2.2
    - pyparsing==3.0.9
    - regex==2022.10.31
    - resampy==0.4.2
    - s3transfer==0.6.0
    - scikit-learn==1.2.1
    - scipy==1.6.3
    - sentencepiece==0.1.97
    - soundfile==0.11.0
    - tensorboardx==2.5.1
    - textgrid==1.5
    - threadpoolctl==3.1.0
    - torch==1.11.0+cu113
    - torchaudio==0.11.0+cu113
    - torchvision==0.12.0+cu113
    - typing-extensions==4.4.0
